const countries =  {'ABW':"Aruba",'AFG':"Afghanistan",'AIA':"Anguila",'ALB':"Albania",'AND':"Andorra",'ARE':"United Arab Emirates",'ARG':"Argentina",
        'ARM':"Armenia",'ASM':"American Samoa",'ATA':"Antarctica",'ATF':"French Southern Territories",'ATG':"Antigua and Barbuda",'AUS':"Australia",
        'AUT':"Austria",'AZE':"Azerbaijan",'BDI':"Burundi",'BEL':"Belgium",'BEN':"Benin",'BES':"Bonaire, Sint Eustatius and Saba",
        'BFA':"Burkina Faso",'BGD':"Bangladesh",'BGR':"Bulgaria",'BHR':"Bahrain",'BHS':"Bahamas",'BIH':"Bosnia and Herzegovina",
        'BLM':"Saint Barthélemy",'BLR':"Belarus",'BLZ':"Belize",'BMU':"Bermuda",'BOL':"Bolivia (Plurinational State of)",
        'BRA':"Brazil",'BRB':"Barbados",'BTN':"Bhutan",'BWA':"Botswana",'CAF':"Central African Republic",'CAN':"Canada",'CCK':"Cocos (Keeling) Islands",
        'CHE':"Switzerland",'CHL':"Chile",'CHN':"China",'CIV':"Côte d'Ivoire",'CMR':"Cameroon",'COD':"Congo, Democratic Republic of the Congo",'COG':"Congo",'COK':"Cook Islands",
        'COL':"Colombia",'COM':"Comoros",'CPV':"Cabo Verde",'CRI':"Costa Rica",'CUB':"Cuba",'CUW':"Curaçao",'CXR':"Christmas Island",
        'CYM':"Cayman Islands",'CYP':"Cyprus",'CZE':"Czechia",'DEU':"Germany",'DJI':"Djibouti",'DMA':"Dominica",'DNK':"Denmark",'DOM':"Dominican Republic",
        'DZA':"Algeria",'ECU':"Ecuador",'EGY':"Egypt",'ERI':"Eritrea",'ESH':"Western Sahara",'ESP':"Spain",'EST':"Estonia",'ETH':"Ethiopia",'FIN':"Finland",
        'FJI':"Fiji",'FRA':"France",'FRO':"Faroe Islands",'FSM':"Micronesia (Federated States of)",'GAB':"Gabon",'GBR':"United Kingdom of Great Britain and Northern Ireland",
        'GEO':"Georgia",'GGY':"Guernsey",'GHA':"Ghana",'GIB':"Gibraltar",'GIN':"Guinea",'GLP':"Guadeloupe",'GMB':"Gambia",'GNB':"Guinea-Bissau",'GNQ':"Equatorial Guinea",
        'GRC':"Greece",'GRD':"Grenada",'GRL':"Greenland",'GTM':"Guatemala",'GUF':"French Guiana",'GUM':"Guam",'GUY':"Guyana",'HKG':"Hong Kong",'HND':"Honduras",
        'HRV':"Croatia",'HTI':"Haiti",'HUN':"Hungary",'IDN':"Indonesia",'IMN':"Isle of Man",'IND':"India",'IOT':"British Indian Ocean Territory",'IRL':"Ireland",
        'IRN':"Iran (Islamic Republic of)",'IRQ':"Iraq",'ISL':"Iceland",'ISR':"Israel",'ITA':"Italy",'JAM':"Jamaica",'JEY':"Jersey",'JOR':"Jordan",'JPN':"Japan",
        'KAZ':"Kazakhstan",'KEN':"Kenya",'KGZ':"Kyrgyzstan",'KHM':"Cambodia",'KIR':"Kiribati",'KNA':"Saint Kitts and Nevis",'KWT':" Kuwait",'LBN':"Lebanon",
        'LBR':"Liberia",'LBY':"Libya",'LCA':"Saint Lucia",'LIE':"Liechtenstein",'LKA':"Sri Lanka",'LSO':"Lesotho",'LTU':"Lithuania",'LUX':"Luxembourg",'LVA':"Latvia",
        'MAC':"Macao",'MAR':"Saint Martin (French part)",'MCO':"",'MDA':"",'MDG':"",'MDV':"",'MEX':"",'MHL':"",'MKD':"",'MLI':"",'MLT':"",'MMR':"",'MNE':"",'MNG':"",'MNP':"",'MOZ':"",'MRT':"",'MSR':"",'MTQ':"",'MUS':"",
        'MWI':"",'MYS':"",'MYT':"",'NAM':"",'NCL':"",'NER':"",'NFK':"",'NGA':"",'NIC':"",'NIU':"",'NLD':"",'NOR':"",'NPL':"",'NRU':"",'NZL':"",'OMN':"",'PAK':"",
        'PAN':"",'PCN':"",'PER':"",'PHL':"",'PLW':"",'PNG':"",'POL':"",'PRI':"",'PRT':"",'PRY':"",'PSE':"",'PYF':"",'QAT':"",'REU':"",'ROU':"",'RUS':"",'RWA':"",
        'SAU':"",'SDN':"",'SEN':"",'SGP':"",'SGS':"",'SHN':"",'SJM':"",'SLB':"",'SLE':"",'SLV':"",'SMR':"",'SOM':"",'SPM':"",'SRB':"",'SSD':"",'STP':"",'SUR':"",
        'SVK':"",'SVN':"",'SWE':"",'SWZ':"",'SYC':"",'SYR':"",'TCA':"",'TCD':"",'TGO':"",'THA':"",'TJK':"",'TKL':"",'TKM':"",'TLS':"",'TON':"",'TTO':"",'TUN':"",
        'TUR':"",'TUV':"",'TWN':"",'TZA':"",'UGA':"",'UKR':"",'URY':"",'USA':"",'UZB':"",'VCT':"",'VEN':"",'VNM':"",'VUT':"",'WLF':"",'WSM':"",'YEM':"",'ZAF':"",
        'ZMB':"",'ZWE':""}



const countryiso = ['ABW','AFG','AIA','ALB','AND','ARE','ARG','ARM','ASM','ATA','ATF','ATG','AUS','AUT','AZE','BDI',
'BEL','BEN','BES','BFA','BGD','BGR','BHR','BHS','BIH','BLM','BLR','BLZ','BMU','BOL','BRA','BRB','BTN',
'BWA','CAF','CAN','CCK','CHE','CHL','CHN','CIV','CMR','COD','COG','COK',
'COL','COM','CPV','CRI','CUB','CUW','CXR','CYM','CYP','CZE','DEU','DJI','DMA','DNK','DOM','DZA','ECU',
'EGY','ERI','ESH','ESP','EST','ETH','FIN','FJI','FRA','FRO','FSM','GAB','GBR','GEO','GGY','GHA','GIB',
'GIN','GLP','GMB','GNB','GNQ','GRC','GRD','GRL','GTM','GUF','GUM','GUY','HKG','HND','HRV','HTI','HUN',
'IDN','IMN','IND','IOT','IRL','IRN','IRQ','ISL','ISR','ITA','JAM','JEY','JOR','JPN','KAZ','KEN','KGZ',
'KHM','KIR','KNA','KWT','LBN','LBR','LBY','LCA','LIE','LKA','LSO','LTU','LUX','LVA','MAC','MAR','MCO',
'MDA','MDG','MDV','MEX','MHL','MKD','MLI','MLT','MMR','MNE','MNG','MNP','MOZ','MRT','MSR','MTQ','MUS',
'MWI','MYS','MYT','NAM','NCL','NER','NFK','NGA','NIC','NIU','NLD','NOR','NPL','NRU','NZL','OMN','PAK',
'PAN','PCN','PER','PHL','PLW','PNG','POL','PRI','PRT','PRY','PSE','PYF','QAT','REU','ROU','RUS','RWA',
'SAU','SDN','SEN','SGP','SGS','SHN','SJM','SLB','SLE','SLV','SMR','SOM','SPM','SRB','SSD','STP','SUR',
'SVK','SVN','SWE','SWZ','SYC','SYR','TCA','TCD','TGO','THA','TJK','TKL','TKM','TLS','TON','TTO','TUN',
'TUR','TUV','TWN','TZA','UGA','UKR','URY','USA','UZB','VCT','VEN','VNM','VUT','WLF','WSM','YEM','ZAF',
'ZMB','ZWE'];